development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: rpostgres://vpxmmpndwttnzc:a6ae36e39b8ba9849c68497bcfbe892771dc65140772a8ede7ee80d5bc02bc46@ec2-23-21-246-11.compute-1.amazonaws.com:5432/d5u8nrpptqlkij
  channel_prefix: testapp_production